#!/bin/sh
   lb config noauto \
        --distribution squeeze \
        --architecture i386 \
        --linux-flavours 686 \
        --bootloader syslinux \
        --binary-images iso \
        --root-command sudo \
        --archive-areas "main contrib non-free" \
        --volatile true \
        --backports true \
        --packages-lists "standard-x11" \
        --package "vtwm mc fbxkb unrar p7zip-full bzip2 tar zip unzip \
        lynx weechat vim rxvt-unicode-lite htop \
        feh xfonts-terminus x11-apps usbutils xosview \
        firmware-linux firmware-linux-free firmware-linux-nonfree \
        suckless-tools acpi laptop-detect" \
        --debian-installer live \
        --debian-installer-gui true \
        --syslinux-splash "/home/arp/arpinux_git/livarp-xxs/splash.png" \
        --hostname "livarp" \
        --iso-volume "Debian Livarp" \
        --iso-publisher "Livarp project; http://arpinux.org/livarp; contact@arpinux.org" \
        --iso-application "Debian Livarp" \
        --memtest none \
        --win32-loader false \
        --verbose \
        --debug \
        --source false \
        --clean \
       "${@}"
